import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">UpdatedHeader</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/location">Location</Link>
        </li>
        <li>
          <Link to="/aboutus">Aboutus</Link>
        </li>
        <li>
          <Link to="/roombooking">Roombooking</Link>
        </li>
        <li>
          <Link to="/checkavailability">Checkavailability</Link>
        </li>
        <li>
          <Link to="/register">Register</Link>
        </li>
        <li>
          <Link to="/payment">Payment</Link>
        </li>
        <li>
          <Link to="/bookingconfirmation">Bookingconfirmation</Link>
        </li>
        <li>
          <Link to="/luxurycottage">Luxurycottage</Link>
        </li>
        <li>
          <Link to="/hertageroom">Hertageroom</Link>
        </li>
        <li>
          <Link to="/villalahari">Villalahari</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
